module.exports = {
    ENVIRONMENT: {
      PRODUCTION: 'production',
      DEVELOPMENT: 'development',
      STAGING: 'staging',
      LOCAL: 'local',
    },
    DEFAULT_COLLECTION: {
      ANSWERED_PRAYERS: 'Answered Prayers',
      UNANSWERED_PRAYERS: 'Unanswered Prayers',
    },
    DAYS: {
      LONG: [
        'Sunday',
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
    },
    MONTHS: {
      SHORT: [
        'Jan',
        'Feb',
        'Mar',
        'Apr',
        'May',
        'Jun',
        'Jul',
        'Aug',
        'Sep',
        'Oct',
        'Nov',
        'Dec',
      ],
      LONG: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ],
    },
}
